{{- if .Values.beat.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shomer.fullname" . }}-beat
  labels:
    {{- include "shomer.labels" . | nindent 4 }}
    app.kubernetes.io/component: beat
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "shomer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: beat
  template:
    metadata:
      labels:
        {{- include "shomer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      serviceAccountName: {{ include "shomer.serviceAccountName" . }}
      {{- with (include "shomer.waitForPostgres" .) }}
      initContainers:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
        - name: beat
          image: "{{ .Values.beat.image.repository }}:{{ .Values.beat.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.beat.image.pullPolicy }}
          command: ["celery", "-A", "shomer.worker", "beat", "--loglevel=info"]
          env:
            {{- include "shomer.commonEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "shomer.credentialsVolumeMount" . | nindent 12 }}
          {{- with .Values.beat.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- include "shomer.credentialsVolume" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
