apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shomer.fullname" . }}-credentials
  labels:
    {{- include "shomer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  {{- if .Values.redis.auth.password }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- end }}
